curl -X POST http://localhost:30080/api/token \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "tenant: root" \
  -d '{
    "email": "admin@root.com",
    "password": "123Pa$$word!"
  }'
